# .github/workflows/main.yml
name: Build and deploy container app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set CI/CD environment variables from AZURE_DEPLOY_SETTINGS
      run: |
        echo "DOCKER_REGISTRY=$(echo '${{ secrets.AZURE_DEPLOY_SETTINGS }}' | jq -r '.DOCKER_REGISTRY')" >> $GITHUB_ENV
        echo "DOCKER_IMAGE_NAME=$(echo '${{ secrets.AZURE_DEPLOY_SETTINGS }}' | jq -r '.DOCKER_IMAGE_NAME')" >> $GITHUB_ENV
        echo "AZURE_CREDENTIALS=$(echo '${{ secrets.AZURE_DEPLOY_SETTINGS }}' | jq -r '.AZURE_CREDENTIALS')" >> $GITHUB_ENV

    - name: Docker registry login
      uses: docker/login-action@v2
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ fromJson(env.AZURE_CREDENTIALS).acrUsername }}
        password: ${{ fromJson(env.AZURE_CREDENTIALS).acrPassword }}

    - name: Set build metadata
      run: |
        echo "APP_VERSION=$(date +'%Y.%m.%d.%H.%M')" >> $GITHUB_ENV
        echo "DEPLOYMENT_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        echo "COMMIT_MESSAGE=${COMMIT_MESSAGE}" >> $GITHUB_ENV
        echo "Commit message: ${COMMIT_MESSAGE}"

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
        file: ./Dockerfile
        build-args: |
          APP_VERSION=${{ env.APP_VERSION }}
          DEPLOYMENT_TIME=${{ env.DEPLOYMENT_TIME }}
          COMMIT_MESSAGE=${{ env.COMMIT_MESSAGE }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Set CI/CD environment variables from AZURE_DEPLOY_SETTINGS
      run: |
        echo "DOCKER_REGISTRY=$(echo '${{ secrets.AZURE_DEPLOY_SETTINGS }}' | jq -r '.DOCKER_REGISTRY')" >> $GITHUB_ENV
        echo "DOCKER_IMAGE_NAME=$(echo '${{ secrets.AZURE_DEPLOY_SETTINGS }}' | jq -r '.DOCKER_IMAGE_NAME')" >> $GITHUB_ENV
        echo "AZURE_CREDENTIALS=$(echo '${{ secrets.AZURE_DEPLOY_SETTINGS }}' | jq -r '.AZURE_CREDENTIALS')" >> $GITHUB_ENV

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}

    - name: Set Azure Web App environment variables from AZURE_APP_SETTINGS
      run: |
        SETTINGS=""
        for row in $(echo '${{ secrets.AZURE_APP_SETTINGS }}' | jq -r 'to_entries[] | "\(.key)=\(.value)"'); do
          KEY=$(echo $row | cut -d '=' -f1)
          VALUE=$(echo $row | cut -d '=' -f2-)
          SETTINGS="$SETTINGS $KEY='$VALUE'"
        done
        echo "Final settings: $SETTINGS"
        az webapp config appsettings set \
          --name ${{ env.DOCKER_IMAGE_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --settings $SETTINGS

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.DOCKER_IMAGE_NAME }}
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
        images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
